version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kpi_course_db
    ports:
      - '5432:5432'
    networks:
      - lab1

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - lab1

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    environment:
      - HOST_DB=db
    depends_on:
      - db
    networks:
      - lab1
    volumes:
     - ./app/main.py:/usr/src/app/main.py
     - ./app:/usr/src/app
     
networks:
  lab1: