-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Students"
(
    "ID" character varying(300) NOT NULL,
    "Birth" integer,
    "SexTypeName" character varying(300),
    "RegName" character varying(300),
    "AreaName" character varying(300),
    "TerName" character varying(300),
    "RegTypeName" character varying(300),
    "TerTypeName" character varying(300),
    "ClassProfileName" character varying(300),
    "ClassLangName" character varying(300),
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Educational_Institutions"
(
    "ID" serial NOT NULL,
    "Name" character varying(300),
    "TypeName" character varying(300),
    "RegName" character varying(300),
    "AreaName" character varying(300),
    "TerName" character varying(300),
    "Parent" character varying(300),
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."EI_of_Students"
(
    "StudentID" character varying(300) NOT NULL,
    "EIID" integer NOT NULL,
    PRIMARY KEY ("StudentID", "EIID")
);

CREATE TABLE IF NOT EXISTS public."Subjects"
(
    "ID" character varying(50) NOT NULL,
    "Name" character varying(300),
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."ZNO_Places"
(
    "StudentID" character varying(300) NOT NULL,
    "SubjectID" character varying(50) NOT NULL,
    "InsitutionID" integer NOT NULL,
    PRIMARY KEY ("StudentID", "SubjectID", "InsitutionID")
);

CREATE TABLE IF NOT EXISTS public."Results_Of_Students"
(
    "StudentID" character varying(300) NOT NULL,
    "SubjectID" character varying(50) NOT NULL,
    "Year" integer,
    "Lang" character varying(100),
    "TestStatus" character varying(100),
    "UkrSubTest" character varying(100),
    "DPALevel" character varying(100),
    "Ball100" double precision,
    "Ball12" double precision,
    "Ball" double precision,
    "AdaptScale" double precision,
    PRIMARY KEY ("StudentID", "SubjectID")
);

ALTER TABLE IF EXISTS public."EI_of_Students"
    ADD FOREIGN KEY ("StudentID")
    REFERENCES public."Students" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EI_of_Students"
    ADD FOREIGN KEY ("EIID")
    REFERENCES public."Educational_Institutions" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ZNO_Places"
    ADD FOREIGN KEY ("StudentID")
    REFERENCES public."Students" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ZNO_Places"
    ADD FOREIGN KEY ("SubjectID")
    REFERENCES public."Subjects" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ZNO_Places"
    ADD FOREIGN KEY ("InsitutionID")
    REFERENCES public."Educational_Institutions" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Results_Of_Students"
    ADD FOREIGN KEY ("StudentID")
    REFERENCES public."Students" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Results_Of_Students"
    ADD FOREIGN KEY ("SubjectID")
    REFERENCES public."Subjects" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;