version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kpi_course_db
    ports:
      - '5432:5432'
    networks:
      - lab2

  pgadmin:
    container_name: pgadmin2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - lab2

  app_data_loading:
    build: 
      context: ./app_data_loading
      dockerfile: Dockerfile-data-loading
    environment:
      - HOST_DB=db
    depends_on:
      - db
    networks:
      - lab2
    volumes:
     - ./app_data_loading/main.py:/app_data_loading/main.py
     - ./app_data_loading/execution_time.txt:/app_data_loading/execution_time.txt

  flyway-migrate:
    build:
      context: ./flyway
      dockerfile: Dockerfile-flyway
    depends_on:
      - app_data_loading
    networks:
      - lab2

  app_query:
    build: 
      context: ./app_query
      dockerfile: Dockerfile-query
    environment:
      - HOST_DB=db
    depends_on:
      - flyway-migrate
    networks:
      - lab2
    volumes:
    - ./app_query/main.py:/app_query/main.py
    - ./app_query/result.csv:/app_query/result.csv
     
networks:
  lab2: